--SCOTT 계정
--10:27:30 PREV_HW>conn scott/pcwk
GRANT SELECT ON dept     TO PREV_HW;
GRANT SELECT ON emp      TO PREV_HW;
GRANT SELECT ON salgrade TO PREV_HW;

--PREV_HW 계정

--10:30:25 SCOTT>conn PREV_HW/ORCL
SELECT * FROM scott.dept;
SELECT * FROM scott.emp;
SELECT * FROM scott.salgrade;

    DEPTNO DNAME                        LOC
---------- ---------------------------- --------------------------
        10 ACCOUNTING                   NEW YORK
        20 RESEARCH                     DALLAS
        30 SALES                        CHICAGO
        40 OPERATIONS                   BOSTON

경   과: 00:00:00.00

     EMPNO ENAME                JOB                       MGR HIREDATE        SAL      COMM     DEPTNO
---------- -------------------- ------------------ ---------- -------- ---------- ---------- ----------
      7369 SMITH                CLERK                    7902 80/12/17        800                   20
      7499 ALLEN                SALESMAN                 7698 81/02/20       1600       300         30
      7521 WARD                 SALESMAN                 7698 81/02/22       1250       500         30
      7566 JONES                MANAGER                  7839 81/04/02       2975                   20
      7654 MARTIN               SALESMAN                 7698 81/09/28       1250      1400         30
      7698 BLAKE                MANAGER                  7839 81/05/01       2850                   30
      7782 CLARK                MANAGER                  7839 81/06/09       2450                   10
      7839 KING                 PRESIDENT                     81/11/17       5000                   10
      7844 TURNER               SALESMAN                 7698 81/09/08       1500         0         30
      7900 JAMES                CLERK                    7698 81/12/03        950                   30
      7902 FORD                 ANALYST                  7566 81/12/03       3000                   20
      7934 MILLER               CLERK                    7782 82/01/23       1300                   10

12 행이 선택되었습니다.

경   과: 00:00:00.02

     GRADE      LOSAL      HISAL
---------- ---------- ----------
         1        700       1200
         2       1201       1400
         3       1401       2000
         4       2001       3000
         5       3001       9999