COL TOTAL      FOR 99
COL SEOUL      FOR 99 
COL GYEONGGI   FOR 99
COL BUSAN      FOR 99
COL ULSAN      FOR 99
COL DAEGU      FOR 99
COL GYEONGNAM  FOR 99

SELECT COUNT(*) TOTAL,
       COUNT(DECODE(t1.area,'02',1) ) AS SEOUL,
       COUNT(DECODE(t1.area,'031',1)) AS GYEONGGI,
       COUNT(DECODE(t1.area,'051',1)) AS BUSAN,
       COUNT(DECODE(t1.area,'052',1)) AS ULSAN,
       COUNT(DECODE(t1.area,'053',1)) AS DAEGU,
       COUNT(DECODE(t1.area,'055',1)) AS GYEONGNAM
FROM (
    SELECT SUBSTR(tel,1, INSTR(tel,')') -1) as area
    FROM student
)t1
;