DROP TABLE tb_pivot;											
											
CREATE TABLE tb_pivot(											
      year VARCHAR2(4 byte),											
      month NUMBER(2)											
);											
											
INSERT INTO tb_pivot VALUES ('2022',1  );											
INSERT INTO tb_pivot VALUES ('2022',2  );											
INSERT INTO tb_pivot VALUES ('2022',3  );											
INSERT INTO tb_pivot VALUES ('2022',4  );											
INSERT INTO tb_pivot VALUES ('2022',5  );											
INSERT INTO tb_pivot VALUES ('2022',6  );											
INSERT INTO tb_pivot VALUES ('2022',7  );											
INSERT INTO tb_pivot VALUES ('2022',8  );											
INSERT INTO tb_pivot VALUES ('2022',9  );											
INSERT INTO tb_pivot VALUES ('2022',10 );											
INSERT INTO tb_pivot VALUES ('2022',11 );											
INSERT INTO tb_pivot VALUES ('2022',12 );											
											
COMMIT;											
										
