--테이블 부분 열 출력
--empno
--ename
--deptno
-- keyword : SELECT, FROM 대문자
-- column,table : 소문자
SELECT empno,
       ename,
       deptno
FROM emp
;
--     EMPNO ENAME                    DEPTNO
------------ -------------------- ----------
--      7369 SMITH                        20
--      7499 ALLEN                        30
--      7521 WARD                         30
--      7566 JONES                        20
--      7654 MARTIN                       30
--      7698 BLAKE                        30
--      7782 CLARK                        10
--      7788 SCOTT                        20
--      7839 KING                         10
--      7844 TURNER                       30
--      7876 ADAMS                        20
--      7900 JAMES                        30
--      7902 FORD                         20
--      7934 MILLER                       10