-- ~~님 good morning!
SELECT ename, 
       'good morning!' "Good"
FROM emp
;
12:09:49 SCOTT>@S10_SELECT_EXPRESSION.SQL

--ENAME                Good
---------------------- --------------------------
--SMITH                good morning!
--ALLEN                good morning!
--WARD                 good morning!
--JONES                good morning!
--MARTIN               good morning!
--BLAKE                good morning!
--CLARK                good morning!
--SCOTT                good morning!
--KING                 good morning!
--TURNER               good morning!
--ADAMS                good morning!
--JAMES                good morning!
--FORD                 good morning!
--MILLER               good morning!
--
--14 행이 선택되었습니다.
--
--경   과: 00:00:00.00